# Generated by Django 3.2.6 on 2021-08-28 12:33

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='label',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='defaultpermission',
            name='announcement',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=5), size=4),
        ),
        migrations.AlterField(
            model_name='defaultpermission',
            name='book',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=5), size=4),
        ),
        migrations.AlterField(
            model_name='defaultpermission',
            name='event',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=5), size=4),
        ),
        migrations.AlterField(
            model_name='defaultpermission',
            name='gallery',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=5), size=4),
        ),
        migrations.AlterField(
            model_name='defaultpermission',
            name='post',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=5), size=4),
        ),
        migrations.AlterField(
            model_name='defaultpermission',
            name='shelf',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=5), size=4),
        ),
        migrations.AlterField(
            model_name='defaultpermission',
            name='story',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=5), size=4),
        ),
        migrations.AlterField(
            model_name='defaultpermission',
            name='suggestion',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=5), size=4),
        ),
        migrations.AlterField(
            model_name='userpermission',
            name='announcement',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=5), size=4),
        ),
        migrations.AlterField(
            model_name='userpermission',
            name='book',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=5), size=4),
        ),
        migrations.AlterField(
            model_name='userpermission',
            name='event',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=5), size=4),
        ),
        migrations.AlterField(
            model_name='userpermission',
            name='gallery',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=5), size=4),
        ),
        migrations.AlterField(
            model_name='userpermission',
            name='post',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=5), size=4),
        ),
        migrations.AlterField(
            model_name='userpermission',
            name='shelf',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=5), size=4),
        ),
        migrations.AlterField(
            model_name='userpermission',
            name='story',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=5), size=4),
        ),
        migrations.AlterField(
            model_name='userpermission',
            name='suggestion',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=5), size=4),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='bio',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='nationality',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('programme', models.CharField(blank=True, max_length=200, null=True)),
                ('start_year', models.CharField(blank=True, max_length=100, null=True)),
                ('end_year', models.CharField(blank=True, max_length=100, null=True)),
                ('is_alumni', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=100, null=True)),
                ('start_year', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
